=== gupta-mukund/xml2802/src/botanica.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="CATALOG">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="PLANT" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="COMMON" type="xs:string" />
                            <xs:element name="BOTANICAL" type="xs:string" />
                            <xs:element name="ZONE" type="xs:integer" />
                            <xs:element name="LIGHT" type="xs:string" />
                            <xs:element name="PRICE">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:decimal">
                                            <xs:attribute name="CURRENCY" type="xs:string"
                                                use="required" />
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== gupta-mukund/xml2802/src/botanica.xml
<?xml version="1.0" encoding="UTF-8"?>

<CATALOG
    xmlns:xsi="http://www.w3.org/2001/XMLSchema"
    xsi:noNamespaceSchemaLocation="botanica.xsd">
    <PLANT>
        <COMMON>Bloodroot</COMMON>
        <BOTANICAL>Sanguinaria canadensis</BOTANICAL>
        <ZONE>4</ZONE>
        <LIGHT>Mostly Shady</LIGHT>
        <PRICE CURRENCY="USD">2.44</PRICE>
    </PLANT>
    <PLANT>
        <COMMON>Columbine</COMMON>
        <BOTANICAL>Aquilegia canadensis</BOTANICAL>
        <ZONE>3</ZONE>
        <LIGHT>Mostly Shady</LIGHT>
        <PRICE CURRENCY="USD">9.37</PRICE>
    </PLANT>
    <PLANT>
        <COMMON>Marsh Marigold</COMMON>
        <BOTANICAL>Caltha palustris</BOTANICAL>
        <ZONE>4</ZONE>
        <LIGHT>Mostly Sunny</LIGHT>
        <PRICE CURRENCY="EURO">6.81</PRICE>
    </PLANT>
</CATALOG>
